# Generated by Django 5.1.5 on 2025-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_trackedproduct_target_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackedproduct',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='trackedproduct',
            name='target_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='trackedproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_tracking'),
        ),
    ]
