# Generated by Django 5.1.5 on 2025-03-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_remove_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
