# Generated by Django 5.1.5 on 2025-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_product_amazon_url_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(default='0 out of 5 stars', max_length=20),
        ),
    ]
