# Generated by Django 5.1.5 on 2025-03-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
