# Generated by Django 5.1.5 on 2025-03-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_remove_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
