# Generated by Django 5.1.5 on 2025-03-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_remove_product_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.customuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
