# Generated by Django 5.1.5 on 2025-03-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(default=dict),
        ),
    ]
