# Generated by Django 5.1.5 on 2025-03-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_product_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
