# Generated by Django 5.1.5 on 2025-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_alter_bestseller_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='product_url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
