# Generated by Django 5.1.5 on 2025-03-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_alter_bestseller_price_alter_bestseller_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestseller',
            old_name='price',
            new_name='current_price',
        ),
    ]
