# Generated by Django 5.1.5 on 2025-03-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_rename_price_bestseller_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
