# Generated by Django 5.1.5 on 2025-03-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_alter_bestseller_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image_url', models.URLField()),
                ('product_url', models.URLField(max_length=1000, unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
