# Generated by Django 6.0.2 on 2026-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0024_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='temporary_default_password', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
