# Generated by Django 5.1.5 on 2026-02-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0025_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_scraped',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
